LLVM_BIN = $(LLVM_BUILD_DIR)/bin

CLANG 		:= clang-16
CLANG++ 	:= clang++-16
LLVM_DIS 	:= llvm-dis-16
LLVM_OPT 	:= opt-16
LLVM_LLI 	:= lli-16
LLVM_LLC 	:= llc-16
LLVM_LINK	:= llvm-link-16
LLVM_MC	  	:= llvm-mc-16

PROJECT_BUILD_DIR = $(COAST_ROOT)/build/
rwildcard=$(wildcard $1$2)$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2))
PROJECT_LIBS := $(call rwildcard,$(PROJECT_BUILD_DIR),*.so)
OPT_LIBS_LOAD = -load $(PROJECT_BUILD_DIR)/TMR/TMR.so

INC_FILES=$(wildcard *.inc)


ifeq ($(BOARD), $(BOARD_HIFIVE1))

include $(LEVEL)/makefiles/Makefile.compile.hiFive1

else ifeq ($(BOARD), $(BOARD_X86))

include $(LEVEL)/makefiles/Makefile.compile.x86

else ifeq ($(BOARD), $(BOARD_LLI))

include $(LEVEL)/makefiles/Makefile.compile.llvmLLI

else ifeq ($(BOARD), $(BOARD_PYNQ))

include $(LEVEL)/makefiles/Makefile.compile.pynq

else ifeq ($(BOARD), $(BOARD_PYNQ_RTOS))

include $(LEVEL)/makefiles/Makefile.compile.pynqrtos

else ifeq ($(BOARD), $(BOARD_ULTRA96))

include $(LEVEL)/makefiles/Makefile.compile.ultra96

else ifeq ($(BOARD), $(BOARD_TMS1224))

include $(LEVEL)/makefiles/Makefile.compile.hercules

else ifeq ($(BOARD), $(BOARD_TMS4357))

include $(LEVEL)/makefiles/Makefile.compile.hercules

else ifeq ($(BOARD), $(BOARD_MSP432))

include $(LEVEL)/makefiles/Makefile.compile.msp432

else ifeq ($(BOARD), $(BOARD_RISCV64))

include $(LEVEL)/makefiles/Makefile.compile.riscv64

else

exe:
	@echo "No compiler for board"
endif
