LEVEL = ..
TARGET = mm_dmr
# OPT_PASSES = -DataflowProtection
# OPT_PASSES = -passes=tmr -countErrors 
OPT_PASSES = -passes=dmr -countErrors -storeDataSync
BOARD = riscv64

include $(LEVEL)/makefiles/Makefile.common
