LEVEL = ..
TARGET = matrixMul_tmr
# OPT_PASSES = -DataflowProtection
# OPT_PASSES = -passes=tmr -countErrors 
OPT_PASSES = -passes=tmr -countErrors -storeDataSync
BOARD = riscv64

include $(LEVEL)/makefiles/Makefile.common
